# cloudformation/taskflow-infrastructure.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'TaskFlow Week 3 Infrastructure - S3, SQS, and RDS'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  ProjectName:
    Type: String
    Default: 'taskflow'
    Description: 'Project name for resource naming'
  DatabasePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: 'Password for RDS database'

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Resources:
  # S3 Bucket for task storage
  TaskStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-storage-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TaskFlowLifecycle
            Status: Enabled
            Prefix: 'tasks/'    # Direct property (Legacy syntax)
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # Dead Letter Queue
  TaskDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-${Environment}-dlq'
      MessageRetentionPeriod: 1209600
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # SQS Queue for task processing
  TaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-${Environment}-queue'
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 10
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TaskDeadLetterQueue.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # VPC for RDS
  TaskFlowVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-vpc'
        - Key: Environment
          Value: !Ref Environment

#   # FIX 2: Route Table for Private Subnets
#   PrivateRouteTable:
#     Type: AWS::EC2::RouteTable
#     Properties:
#       VpcId: !Ref TaskFlowVPC
#       Tags:
#         - Key: Name
#           Value: !Sub '${ProjectName}-${Environment}-private-rt'

# # FIX 2: S3 Gateway Endpoint (Allows private subnets to reach S3)
#   S3Endpoint:
#     Type: AWS::EC2::VPCEndpoint
#     Properties:
#       VpcId: !Ref TaskFlowVPC
#       ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
#       VpcEndpointType: Gateway
#       RouteTableIds:
#         - !Ref PrivateRouteTable